### PR TITLE
Fix HttpShardHandlerFactory to use an unbounded queue if the pool siz…

### PR DESCRIPTION
**Pull request by timatbw**
…e is limited, to avoid rejected tasks in wide distributed searches

### CODE REVIEW

**Comment by mkavanagh** [comment]
Is this going to have the same problem that non-fixed thread pool executors in java normally have, where it will only start new threads beyond the core pool when the queue is full?

**Comment by timatbw** [comment]
Will double-check.. it's using ThreadPoolExecutor.execute and the source of that calls `.offer` on the queue, then if that succeeds (which it always should for an unbounded queue) it checks on the worker pool size.

**Comment by timatbw** [comment]
Good shout - it does indeed only use the core pool size and never expands. Given that we'll be using these threads all the time, we might as well make it a fixed pool by setting `corePoolSize` to the same as `maximumPoolSize`. Trying that does what we want (use upto that many threads and have the remaining tasks wait in the queue).

**Review by brandwatchsteve — APPROVED** [review]
looks good to me (from my limited java) - we can test this out more fully on stage though

**Comment by timatbw** [comment]
we do need to set both pool size configuration values to the same though, both max and core, along with this change

**Pull request merged**
