### PR TITLE
Remove throttling of merges during expunge

### PR DESCRIPTION
**Pull request by timatbw**

### CODE REVIEW

**Review by spmason — COMMENTED** [review]
It looks like something (not sure what - a plugin?) could just call the `disableAutoIOThrottle` method instead?

**Comment by timatbw** [comment]
Yeah that's the problem, there's nowhere to call it.. the solrconfig.xml doesn't allow you to specify that method should be called on the singleton when configuring solr. You can call setX bean methods, but not this one 😞

**Comment by spmason** [comment]
Is it worth making that possible and PRing it upstream? Or just turning this into a system property?

**Review by brandwatchsteve — APPROVED** [review]
lgtm! 

I definitely agree that this would be good to make configurable, but I want to roll out this with urgency now (and we don't have any solr6 instances which aren't on ssd)

**Comment by timatbw** [comment]
sys prop might be a good approach yeah, I don't see that we want throttling (as we're using SSDs) and someone else has complained about this before .. http://lucene.472066.n3.nabble.com/ConcurrentMergeScheduler-options-not-exposed-td4282521.html

There is facility to configure the scheduler, with set methods, will see how ugly it would be to support this flag like it was a setX boolean method.

**Comment by timatbw** [comment]
Happy to work on a proper upstream-able fix in another PR if we want to find out if this actually works in practice (by making this crude change first)

**Comment by spmason** [comment]
I also wonder if we should just have _some_ limit on the throttling - even if it's really high - to avoid saturating disks when many merges run at once?

**Comment by timatbw** [comment]
Looking at the code, it seems to be either automatic, or off (with no limit).. there's no facility to set a manual maximum rate. But it doesn't look difficult to add that, so I think I will (and have that default to unlimited, as it is now).

There is some ugly configuration for that class already (because someone removed a couple of set methods and added a dual value set method, so now the configuration has to handle that as a special case) and I've added support for using a boolean in the XML config which then calls the enable/disable methods. PR coming soon..

**Pull request merged**
